# Nome do serviço
spring.application.name=adoption-service

# Porta
server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://localhost:9090/eureka/

# Banco H2
spring.datasource.url=jdbc:h2:mem:adoptiondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest