# Nome do serviço
spring.application.name=animal-service

# Porta (diferente do user-service)
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:9090/eureka/

# H2
spring.datasource.url=jdbc:h2:mem:animaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true