# Nome da aplicação
spring.application.name=eureka-server

# Porta padrão do Eureka
server.port=9090

# Configuração do Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL padrão (opcional, mas recomendado)
eureka.client.service-url.defaultZone=http://localhost:9090/eureka/

# Evita logs desnecessários (opcional)
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF